#!/usr/bin/env bash
#Pings an IP address passed as an argument
#Accepts a string as an argument
#Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
#Ping the IP 5 times

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
